version: '3.9'

services:
  orders-app:
    build: ./
    command: ./wait-for-postgres.sh db ./orders-app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - nats-streaming
      - redis
    environment:
#     username: "postgres"
      host: db
      host_cash: redis
      host_nats: nats-streaming
      DB_PASSWORD: qwerty
      DB_DSN: 'postgres://user:password@db:5432/utp'
    networks: ["nats"]

  #      port: "5432"
#      dbname: "postgres"
#      sslmode: "disable"
#
#      DB_HOST: db
#      DB_PORT: 5432
#      DB_USER: postgres
#      DB_PASSWORD: qwerty
#      DB_NAME: postgres

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: utp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    networks: ["nats"]

  nats-streaming:
    restart: always
    image: nats-streaming:latest
    ports:
      - "4222:4222"
    networks: ["nats"]
  redis:
      restart: always
      image: redis:latest
      ports:
        - "6379:6379"
      networks: [ "nats" ]
networks:
  nats:
    name: nats