port: "8000"

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

cash:
  host_cash: "localhost"
  port: "6379"
  password: ""
  dbname: "0"

nats-streaming:
  port: 4222
  host_nats: "localhost"

